"""
LLM-grounded XAI worker.

Replaces the static template engine for action-transition events with prose
generated by Claude Haiku, while keeping the synchronous template path as a
zero-regression fallback.

Design (per upgrade-ai-layer plan, Deliverable 3):

  * The main `agent_service.telemetry_loop` publishes `ai.recommendation`
    immediately with the template reason — no LLM in the hot path.
  * On *action-transitions* (`rec.action_label != self._last_label`), a job
    is enqueued to this module's bounded queue.
  * A daemon worker thread drains the queue, calls Anthropic Haiku, publishes
    a follow-up `ai.xai_refresh` event keyed by (timestamp, machine_id) so
    the dashboard can patch the row in place.
  * If `ANTHROPIC_API_KEY` is missing, the worker logs once and disables
    itself; nothing else changes.
  * If a per-call request fails, the failure is logged and no refresh is
    emitted — the template reason already on `ai.recommendation` stays.

Cache key: (action_label, dominant_reason, severity_bucket). Bucketed by
machine_health (SAFE/WARNING/CRITICAL) so we don't re-explain identical
situations. TTL 1h.

Prompt caching: a stable system prompt block (~1500 tokens of bilingual style
guide + reward formula + state vocab) is marked `cache_control: ephemeral`,
so subsequent calls hit cache and pay ~0.1x cost / ~300ms latency.
"""

from __future__ import annotations

import json
import logging
import os
import queue
import threading
import time
from dataclasses import dataclass
from typing import Any, Dict, Optional, Tuple

_log = logging.getLogger("ai.llm_xai")

try:
    import anthropic
except ImportError:  # pragma: no cover
    anthropic = None  # type: ignore


# ── Tunables ───────────────────────────────────────────────────────────────

MODEL = os.getenv("LLM_XAI_MODEL", "claude-haiku-4-5-20251001")
QUEUE_MAX = 32
CACHE_MAX = 256
CACHE_TTL_SEC = 3600  # 1 hour
REQUEST_MAX_TOKENS = 400  # bilingual reasons are short — 2-3 sentences each


SYSTEM_PROMPT = """You are the operator-facing explainability layer for Opti-Twin, an AI control system for an Electric Arc Furnace (EAF) at an Egyptian steel mill (Ezz Steel, Ain Sokhna).

Your job: take a structured recommendation from the RL policy and produce a short, operator-grade explanation in BOTH English and Arabic. The explanation must reference the actual telemetry values supplied — no generic boilerplate.

# Action vocabulary (7 actions)
- HOLD_STEADY: keep current setpoints; no change required.
- REDUCE_ARC_POWER: reduce furnace arc power by ~15 MW; saves energy when not productive.
- RAISE_PF_COMPENSATION: engage capacitor bank to raise power factor toward 0.92 reference; avoids EgyptERA penalty.
- EMERGENCY_COOLING: increase cooling water flow + reduce arc; protects refractory wall above 200°C.
- PRE_PEAK_DROP: reduce arc ahead of TOU peak window (18:00–22:00); avoids peak billing.
- GRID_RIDE_THROUGH: cap arc at 60 MW when grid frequency drops below 49.7 Hz; protects equipment + grid.
- TRANSFORMER_DERATE: cap arc at 75 MW on transformer thermal alarm; extends insulation life.

# Reward decomposition (multi-objective)
R = α·E_saved − β·M_stress − γ·P_delay + δ·Quality − ε·Wear − ζ·PF_penalty
The "dominant_reason" tells you which component drove this action.

# Safety-mask context
If `safety_overridden` is true, the policy's chosen action was overridden by the hard-limit safety mask. The `safety_reason` field identifies which limit fired:
- wall_over_limit: wall_panel_temp ≥ 250°C, forced EMERGENCY_COOLING
- grid_freq_low: grid_frequency < 49.7 Hz, forced GRID_RIDE_THROUGH
- transformer_alarm: transformer alarm fired, forced TRANSFORMER_DERATE
- bath_freeze_risk: furnace_bath_temp < 1500°C, blocked downward power moves

When the mask fires, name the limit explicitly and frame the action as protective — not as a policy choice.

# Tone
- Direct, factual, operator-grade. No hedging, no "consider" or "might want to". No emoji.
- Cite the actual numeric value when relevant (temperature, PF, price, frequency).
- 1-3 sentences per language. Brief.
- Arabic must be natural Egyptian-MSA technical register, not machine-translated literal English. Use the same numeric values.

You will receive the recommendation as a user message and call the `emit_explanation` tool with `reason_en` and `reason_ar`. Always call the tool — never reply in plain text."""


EMIT_TOOL = {
    "name": "emit_explanation",
    "description": "Emit the bilingual operator-facing explanation for this recommendation.",
    "input_schema": {
        "type": "object",
        "properties": {
            "reason_en": {
                "type": "string",
                "description": "1–3 sentence English explanation, citing actual telemetry values.",
            },
            "reason_ar": {
                "type": "string",
                "description": "1–3 sentence Arabic explanation, same values, natural technical register.",
            },
        },
        "required": ["reason_en", "reason_ar"],
    },
}


# ── Data shapes ─────────────────────────────────────────────────────────────


@dataclass
class XAIJob:
    timestamp: Any
    machine_id: Any
    action_label: str
    raw_action_label: Optional[str]
    safety_overridden: bool
    safety_reason: Optional[str]
    dominant_reason: str
    machine_health: str  # SAFE / WARNING / CRITICAL
    reward_components: Dict[str, float]
    state_excerpt: Dict[str, Any]  # selected fields only — see _build_user_prompt


# ── Worker ──────────────────────────────────────────────────────────────────


class LLMXAIWorker:
    """Async LLM enrichment worker. Disabled (no-op) if API key missing."""

    def __init__(self, redis_client: Any) -> None:
        self.r = redis_client
        self.q: "queue.Queue[XAIJob]" = queue.Queue(maxsize=QUEUE_MAX)
        self._cache: Dict[Tuple[str, str, str], Tuple[float, Dict[str, str]]] = {}
        self._cache_lock = threading.Lock()
        self._client: Optional[Any] = None
        self._enabled = False
        self._dropped = 0
        self._processed = 0

        api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
        if not api_key:
            _log.info("LLM XAI disabled (no ANTHROPIC_API_KEY); template engine remains in use")
            return
        if anthropic is None:
            _log.warning("LLM XAI disabled (anthropic SDK not importable)")
            return
        try:
            self._client = anthropic.Anthropic(api_key=api_key)
            self._enabled = True
            _log.info("LLM XAI worker started (model=%s)", MODEL)
        except Exception as exc:  # pragma: no cover
            _log.warning("LLM XAI disabled (client init failed: %s)", exc)

    @property
    def enabled(self) -> bool:
        return self._enabled

    def start(self) -> None:
        if not self._enabled:
            return
        threading.Thread(target=self._run, daemon=True, name="llm-xai-worker").start()

    def submit(self, job: XAIJob) -> None:
        if not self._enabled:
            return
        try:
            self.q.put_nowait(job)
        except queue.Full:
            self._dropped += 1
            if self._dropped % 10 == 1:
                _log.warning("LLM XAI queue full; dropped %d jobs total", self._dropped)

    def _run(self) -> None:
        while True:
            job = self.q.get()
            try:
                self._handle(job)
            except Exception as exc:  # pragma: no cover
                _log.warning("LLM XAI handler error: %s", exc)
            finally:
                self.q.task_done()

    # ── Per-job pipeline ───────────────────────────────────────────────────

    def _handle(self, job: XAIJob) -> None:
        cache_key = (job.action_label, job.dominant_reason, job.machine_health)
        cached = self._cache_get(cache_key)
        if cached is not None:
            self._publish_refresh(job, cached, source="cache")
            return

        result = self._call_llm(job)
        if result is None:
            return
        self._cache_put(cache_key, result)
        self._publish_refresh(job, result, source="llm")
        self._processed += 1

    def _cache_get(self, key: Tuple[str, str, str]) -> Optional[Dict[str, str]]:
        with self._cache_lock:
            entry = self._cache.get(key)
            if entry is None:
                return None
            ts, payload = entry
            if time.time() - ts > CACHE_TTL_SEC:
                del self._cache[key]
                return None
            return payload

    def _cache_put(self, key: Tuple[str, str, str], payload: Dict[str, str]) -> None:
        with self._cache_lock:
            if len(self._cache) >= CACHE_MAX:
                # Evict the oldest entry (cheap LRU approximation)
                oldest = min(self._cache.items(), key=lambda kv: kv[1][0])[0]
                del self._cache[oldest]
            self._cache[key] = (time.time(), payload)

    def _call_llm(self, job: XAIJob) -> Optional[Dict[str, str]]:
        assert self._client is not None
        try:
            resp = self._client.messages.create(
                model=MODEL,
                max_tokens=REQUEST_MAX_TOKENS,
                system=[
                    {
                        "type": "text",
                        "text": SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                tools=[EMIT_TOOL],
                tool_choice={"type": "tool", "name": "emit_explanation"},
                messages=[{"role": "user", "content": _build_user_prompt(job)}],
            )
        except Exception as exc:
            _log.warning("LLM XAI request failed (action=%s): %s", job.action_label, exc)
            return None

        for block in resp.content:
            if getattr(block, "type", None) == "tool_use" and block.name == "emit_explanation":
                inp = block.input or {}
                en = str(inp.get("reason_en", "")).strip()
                ar = str(inp.get("reason_ar", "")).strip()
                if en and ar:
                    return {"reason_en": en, "reason_ar": ar}
        _log.warning("LLM XAI response had no usable tool_use block (action=%s)", job.action_label)
        return None

    def _publish_refresh(self, job: XAIJob, payload: Dict[str, str], *, source: str) -> None:
        event = {
            "timestamp": job.timestamp,
            "machine_id": job.machine_id,
            "action_label": job.action_label,
            "xai_reason_en": payload["reason_en"],
            "xai_reason_ar": payload["reason_ar"],
            "source": source,  # "llm" | "cache"
        }
        try:
            self.r.publish("ai.xai_refresh", json.dumps(event))
        except Exception as exc:
            _log.warning("Publish ai.xai_refresh failed: %s", exc)


def _build_user_prompt(job: XAIJob) -> str:
    """Compact, deterministic user prompt — keeps cache-stable structure."""
    rc = {k: round(float(v), 2) for k, v in job.reward_components.items() if k != "total"}
    state = job.state_excerpt
    lines = [
        f"action_label: {job.action_label}",
    ]
    if job.safety_overridden:
        lines.append(f"safety_overridden: true (reason={job.safety_reason})")
        if job.raw_action_label and job.raw_action_label != job.action_label:
            lines.append(f"policy_wanted: {job.raw_action_label} (overridden by mask)")
    lines.extend([
        f"dominant_reason: {job.dominant_reason}",
        f"machine_health: {job.machine_health}",
        f"reward_components: {json.dumps(rc, sort_keys=True)}",
        f"state: {json.dumps(state, sort_keys=True)}",
    ])
    return "\n".join(lines)


# ── State excerpt helper (used by agent_service) ────────────────────────────

_RELEVANT_STATE_KEYS = (
    "wall_panel_temp",
    "furnace_bath_temp",
    "electrode_temp",
    "power_factor",
    "arc_power_mw",
    "grid_frequency",
    "electricity_price",
    "is_peak",
    "sim_hour",
    "heat_progress_pct",
    "production_backlog",
)


def excerpt_state(state: Dict[str, Any]) -> Dict[str, Any]:
    """Extract the state fields the LLM cares about; rounds floats."""
    out: Dict[str, Any] = {}
    for k in _RELEVANT_STATE_KEYS:
        if k in state:
            v = state[k]
            if isinstance(v, float):
                out[k] = round(v, 2)
            else:
                out[k] = v
    return out
